Numpy

In [5]:
# Numeric Python 
# Alternative to Python List: NumPy Array 
# Calculations over entire arrays
# Easy and Fast 
# Installation
# pip3 install numpy

In [7]:
# Import numpy
import numpy as np
height_in = [71,73,84,22,45]
# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)
# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in*0.0254

# Print np_height_m
print(np_height_m)


[71 73 84 22 45]
[1.8034 1.8542 2.1336 0.5588 1.143 ]


In [9]:
weight_lb = [180, 215, 210, 210, 188]
# Import numpy
import numpy as np


# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592
# Calculate the BMI: bmi

bmi = np_weight_kg/np_height_m**2

# Print out bmi
print(bmi)

[ 25.10462629  28.36551629  20.9246728  305.05060184  65.27257934]


In [10]:
# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the numpy array with name light 
# if the corresponding baseball player's bmi is below 21

light = bmi < 21


# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21

print(bmi[light])

[False False  True False False]
[20.9246728]


In [11]:
# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 4 in numpy array
print(np_weight_lb[4])

# Print out sub-array of np_height_in: index 1 up to and including index 4 in numpy array
print(np_height_in[1:5])

188
[73 84 22 45]


2D Numpy Array

In [13]:
# Import numpy
import numpy as np

# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball

np_baseball  = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [20]:

# Import numpy package
import numpy as np

# Create np_baseball 
np_baseball = np.array(baseball)

# Print out the 4th row of np_baseball
print(np_baseball[3])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:, 1]
print(np_weight_lb)

# Print out height of 3rd player
print(np_baseball[2][0])

[188.   75.2]
[215.  102.7]
210.0


In [29]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print("--------------")
print(np_mat + np.array([10, 10]))
print("--------------")

print(np_mat + np_mat)



[[ 2  4]
 [ 6  8]
 [10 12]]
--------------
[[11 12]
 [13 14]
 [15 16]]
--------------
[[ 2  4]
 [ 6  8]
 [10 12]]
